on: 
    push: 
        branches: [master]

jobs:
    test-code:
        runs-on: ubuntu-latest
        name: Test python code
        steps:
            - name: Checkout
              uses: actions/checkout@main
            - name: Set up Python 3.10
              uses: actions/setup-python@v3
              with:
                python-version: "3.10"
            - name: Install pytest
              run: |
                python -m pip install pytest
            - name: Install pytest
              run: |
                python -m pytest main.py
            